# Generated by Django 2.1 on 2018-08-09 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('royaleAVB', models.FloatField(blank=True, default=0.0, null=True)),
                ('checkingAVB', models.FloatField(blank=True, default=0.0, null=True)),
                ('royalePNB', models.FloatField(blank=True, default=0.0, null=True)),
                ('checkingPNB', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.IntegerField(default=1533844009360)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('account_number', models.CharField(default=0, max_length=20)),
                ('secret_key', models.CharField(default=0, max_length=256)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.IntegerField(default=1533844009359)),
            ],
        ),
    ]
