# Generated by Django 2.1 on 2018-08-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0002_auto_20180809_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='created_at',
            field=models.IntegerField(default=1533844681),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.IntegerField(default=1533844681),
        ),
    ]
