# Generated by Django 2.1 on 2018-08-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0008_auto_20180811_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiftcode',
            name='created_at',
            field=models.IntegerField(default=1533944679),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='created_at',
            field=models.IntegerField(default=1533944679),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='created_at',
            field=models.IntegerField(default=1533944679),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.IntegerField(default=1533944679),
        ),
    ]
