# Generated by Django 2.1 on 2018-08-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0009_auto_20180811_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='htmlTemplate',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='swiftcode',
            name='created_at',
            field=models.IntegerField(default=1533945259),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='created_at',
            field=models.IntegerField(default=1533945259),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='created_at',
            field=models.IntegerField(default=1533945259),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.IntegerField(default=1533945259),
        ),
    ]
