# Generated by Django 2.1 on 2018-08-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0010_auto_20180811_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiftcode',
            name='created_at',
            field=models.IntegerField(default=1534106890),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='amount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='created_at',
            field=models.IntegerField(default=1534106890),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='created_at',
            field=models.IntegerField(default=1534106890),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.IntegerField(default=1534106890),
        ),
    ]
