# Generated by Django 2.1 on 2018-08-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0012_auto_20180813_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.IntegerField(default=1534148017)),
            ],
        ),
        migrations.DeleteModel(
            name='Enqiury',
        ),
        migrations.AlterField(
            model_name='swiftcode',
            name='created_at',
            field=models.IntegerField(default=1534148017),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='created_at',
            field=models.IntegerField(default=1534148017),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='created_at',
            field=models.IntegerField(default=1534148017),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.IntegerField(default=1534148017),
        ),
    ]
